# Generated by Django 2.2.19 on 2023-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20230619_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='IceCream/', verbose_name='Зображення'),
        ),
    ]
